#!/bin/bash

input="/Users/adammork/Desktop/Ended Reservations in My Actuvity.mov"
FPS=20
ffmpeg -y -i "$input" -filter_complex "[0:v] fps=12,scale=if(gte(iw\,ih)\,min(540\,iw)\,-2):if(lt(iw\,ih)\,min(540\,ih)\,-2),split [a][b];[a] palettegen [p];[b][p] paletteuse" -r $FPS -f gif "/Users/adammork/Desktop/test_mini.gif"
